- alias: zapit
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: catercorner16
  name: catercorner16
- alias: zap-it
  config:
    configmap: controller-conf
    namespace: bungalow55-hasura
  data: null
  kubeContext: bungalow55
  name: bungalow55
